default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: my_database_development

test:
  <<: *default
  adapter: sqlite3
  database: my_database_test

production:
  <<: *default
  adapter: postgresql
  database: my_database_production